### ISSUE TITLE
Spam Bug

### ISSUE THREAD

**Issue by betester** [betester/Suara#1]
2022-08-26T09:43:47.883480+00:00 app[worker.1]: TypeError: Invalid argument type
2022-08-26T09:43:47.883481+00:00 app[worker.1]:     at encodeCommand (/app/node_modules/@redis/client/dist/lib/client/RESP2/encoder.js:17:19)
2022-08-26T09:43:47.883482+00:00 app[worker.1]:     at RedisCommandsQueue.getCommandToSend (/app/node_modules/@redis/client/dist/lib/client/commands-queue.js:187:45)
2022-08-26T09:43:47.883483+00:00 app[worker.1]:     at Commander._RedisClient_tick (/app/node_modules/@redis/client/dist/lib/client/index.js:440:76)
2022-08-26T09:43:47.883483+00:00 app[worker.1]:     at Commander._RedisClient_sendCommand (/app/node_modules/@redis/client/dist/lib/client/index.js:424:82)
2022-08-26T09:43:47.883484+00:00 app[worker.1]:     at Commander.commandsExecutor (/app/node_modules/@redis/client/dist/lib/client/index.js:170:154)
2022-08-26T09:43:47.883484+00:00 app[worker.1]:     at Commander.BaseClass.<computed> [as sRem] (/app/node_modules/@redis/client/dist/lib/commander.js:8:29)
2022-08-26T09:43:47.883485+00:00 app[worker.1]:     at handleUserAction (/app/src/events/voiceStateUpdate.js:41:23)
2022-08-26T09:43:47.883486+00:00 app[worker.1]:     at /app/src/events/voiceStateUpdate.js:5:24
2022-08-26T09:43:47.883486+00:00 app[worker.1]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-08-26T09:43:47.883486+00:00 app[worker.1]:     at async module.exports (/app/src/events/voiceStateUpdate.js:71:24)
2022-08-26T09:43:47.883487+00:00 app[worker.1]: Emitted 'error' event on Client instance at:
2022-08-26T09:43:47.883492+00:00 app[worker.1]:     at emitUnhandledRejectionOrErr (node:events:394:10)
2022-08-26T09:43:47.883492+00:00 app[worker.1]:     at processTicksAndRejections (node:internal/process/task_queues:85:21)

**Comment by betester** [comment]
Possibilities number 1
The problem arises because of concurrency race condition. take for example, we have 2 users A and B. A and B spams the switching channels. at some point, the current users on the channel are A and B and on the database it is also A and B ( it shouldn't but because of the previous calls have not finished writing, this happens ). 
when the program checks, there are no users that moved hence the error showed up.

Fix:
I don't know
